// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddvivqswyaucpdblptkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdml2cXN3eWF1Y3BkYmxwdGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NTkyMDgsImV4cCI6MjA4NjEzNTIwOH0.xydL3ZC-XGN6gh4jinwaSdv4LX3kgVIaGT5Yb1afDPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});